# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "Gemfile"
    - "lib/tasks/*.rake"
    - "bin/*"
    - "config/puma.rb"
    - "config/spring.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"
    - "vendor/**/*"   # Exclude vendor safely

Style/Documentation:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true
  Width: 5
